// Static content that doesn't change and is not managed through CMS
export const staticContent = {
  en: {
    // Navigation and Layout
    navigation: {
      home: "Home",
      about: "About",
      research: "Research",
      contact: "Contact",
      language: "Language",
      theme: "Theme"
    },
    
    // Common UI Elements
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      view: "View",
      download: "Download",
      upload: "Upload",
      submit: "Submit",
      reset: "Reset",
      close: "Close",
      back: "Back",
      next: "Next",
      previous: "Previous",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      refresh: "Refresh",
      copy: "Copy",
      share: "Share",
      print: "Print",
      export: "Export",
      import: "Import"
    },
    
    // Form Labels
    forms: {
      name: "Name",
      email: "Email",
      phone: "Phone",
      subject: "Subject",
      message: "Message",
      password: "Password",
      confirmPassword: "Confirm Password",
      firstName: "First Name",
      lastName: "Last Name",
      company: "Company",
      position: "Position",
      website: "Website",
      address: "Address",
      city: "City",
      country: "Country",
      zipCode: "ZIP Code",
      required: "Required",
      optional: "Optional"
    },
    
    // Button Labels
    buttons: {
      downloadCV: "Download CV",
      getInTouch: "Get in Touch",
      sendMessage: "Send Message",
      viewAll: "View All",
      learnMore: "Learn More",
      readMore: "Read More",
      contactMe: "Contact Me",
      viewProfile: "View Profile",
      connect: "Connect",
      follow: "Follow",
      subscribe: "Subscribe",
      join: "Join",
      apply: "Apply",
      register: "Register",
      login: "Login",
      logout: "Logout",
      signup: "Sign Up",
      forgotPassword: "Forgot Password",
      resetPassword: "Reset Password",
      changePassword: "Change Password",
      updateProfile: "Update Profile"
    },
    
    // Status Messages
    status: {
      messageSent: "Message sent successfully!",
      messageError: "Error sending message. Please try again.",
      sending: "Sending...",
      loading: "Loading...",
      saving: "Saving...",
      updating: "Updating...",
      deleting: "Deleting...",
      uploading: "Uploading...",
      downloading: "Downloading...",
      processing: "Processing...",
      connecting: "Connecting...",
      disconnected: "Disconnected",
      connected: "Connected",
      online: "Online",
      offline: "Offline",
      available: "Available",
      unavailable: "Unavailable",
      busy: "Busy",
      away: "Away"
    },
    
    // Error Messages
    errors: {
      required: "This field is required",
      invalidEmail: "Please enter a valid email address",
      invalidPhone: "Please enter a valid phone number",
      invalidUrl: "Please enter a valid URL",
      passwordMismatch: "Passwords do not match",
      passwordTooShort: "Password must be at least 8 characters",
      invalidFormat: "Invalid format",
      fileTooLarge: "File size is too large",
      unsupportedFile: "Unsupported file type",
      networkError: "Network error. Please try again.",
      serverError: "Server error. Please try again later.",
      unauthorized: "Unauthorized access",
      forbidden: "Access forbidden",
      notFound: "Page not found",
      timeout: "Request timeout",
      unknownError: "An unknown error occurred"
    },
    
    // Success Messages
    success: {
      profileUpdated: "Profile updated successfully",
      messageSent: "Message sent successfully",
      fileUploaded: "File uploaded successfully",
      fileDownloaded: "File downloaded successfully",
      changesSaved: "Changes saved successfully",
      itemDeleted: "Item deleted successfully",
      itemCreated: "Item created successfully",
      itemUpdated: "Item updated successfully",
      passwordChanged: "Password changed successfully",
      emailSent: "Email sent successfully",
      registrationComplete: "Registration completed successfully",
      loginSuccessful: "Login successful"
    },
    
    // Placeholder Text
    placeholders: {
      search: "Search...",
      enterName: "Enter your name",
      enterEmail: "Enter your email",
      enterPhone: "Enter your phone number",
      enterMessage: "Enter your message",
      enterSubject: "Enter subject",
      enterPassword: "Enter your password",
      confirmPassword: "Confirm your password",
      enterAddress: "Enter your address",
      enterCompany: "Enter company name",
      enterPosition: "Enter your position",
      enterWebsite: "Enter website URL",
      selectCountry: "Select country",
      selectLanguage: "Select language",
      selectTheme: "Select theme",
      uploadFile: "Upload file",
      dragAndDrop: "Drag and drop files here",
      noResults: "No results found",
      noData: "No data available"
    },
    
    // Tooltips
    tooltips: {
      downloadCV: "Download my CV/Resume",
      contactMe: "Send me a message",
      viewProfile: "View my full profile",
      connectLinkedIn: "Connect on LinkedIn",
      followTwitter: "Follow on Twitter",
      subscribeNewsletter: "Subscribe to newsletter",
      shareProfile: "Share my profile",
      copyEmail: "Copy email address",
      copyPhone: "Copy phone number",
      viewLocation: "View on map",
      openWebsite: "Visit website",
      downloadFile: "Download file",
      previewFile: "Preview file",
      editItem: "Edit this item",
      deleteItem: "Delete this item",
      viewDetails: "View details",
      closeModal: "Close modal",
      minimizeWindow: "Minimize window",
      maximizeWindow: "Maximize window",
      fullscreen: "Toggle fullscreen"
    },
    
    // Accessibility
    accessibility: {
      menuButton: "Toggle navigation menu",
      closeButton: "Close",
      searchButton: "Search",
      languageButton: "Change language",
      themeButton: "Toggle theme",
      scrollToTop: "Scroll to top",
      skipToContent: "Skip to main content",
      skipToNavigation: "Skip to navigation",
      loadingSpinner: "Loading content",
      errorIcon: "Error occurred",
      successIcon: "Operation successful",
      warningIcon: "Warning",
      infoIcon: "Information",
      helpIcon: "Help",
      settingsIcon: "Settings",
      profileIcon: "User profile",
      notificationIcon: "Notifications",
      searchIcon: "Search",
      filterIcon: "Filter options",
      sortIcon: "Sort options",
      refreshIcon: "Refresh content",
      downloadIcon: "Download",
      uploadIcon: "Upload",
      shareIcon: "Share",
      printIcon: "Print",
      exportIcon: "Export",
      importIcon: "Import",
      editIcon: "Edit",
      deleteIcon: "Delete",
      viewIcon: "View",
      addIcon: "Add",
      removeIcon: "Remove",
      saveIcon: "Save",
      cancelIcon: "Cancel",
      backIcon: "Go back",
      forwardIcon: "Go forward",
      homeIcon: "Go to home",
      aboutIcon: "Go to about",
      contactIcon: "Go to contact",
      researchIcon: "Go to research"
    }
  },
  
  ja: {
    // Navigation and Layout
    navigation: {
      home: "ホーム",
      about: "私について",
      research: "研究",
      contact: "お問い合わせ",
      language: "言語",
      theme: "テーマ"
    },
    
    // Common UI Elements
    common: {
      loading: "読み込み中...",
      error: "エラー",
      success: "成功",
      cancel: "キャンセル",
      save: "保存",
      edit: "編集",
      delete: "削除",
      view: "表示",
      download: "ダウンロード",
      upload: "アップロード",
      submit: "送信",
      reset: "リセット",
      close: "閉じる",
      back: "戻る",
      next: "次へ",
      previous: "前へ",
      search: "検索",
      filter: "フィルター",
      sort: "並び替え",
      refresh: "更新",
      copy: "コピー",
      share: "共有",
      print: "印刷",
      export: "エクスポート",
      import: "インポート"
    },
    
    // Form Labels
    forms: {
      name: "お名前",
      email: "メールアドレス",
      phone: "電話番号",
      subject: "件名",
      message: "メッセージ",
      password: "パスワード",
      confirmPassword: "パスワード確認",
      firstName: "名",
      lastName: "姓",
      company: "会社名",
      position: "役職",
      website: "ウェブサイト",
      address: "住所",
      city: "市区町村",
      country: "国",
      zipCode: "郵便番号",
      required: "必須",
      optional: "任意"
    },
    
    // Button Labels
    buttons: {
      downloadCV: "履歴書をダウンロード",
      getInTouch: "お問い合わせ",
      sendMessage: "メッセージを送信",
      viewAll: "すべて表示",
      learnMore: "詳細を見る",
      readMore: "続きを読む",
      contactMe: "お問い合わせ",
      viewProfile: "プロフィールを見る",
      connect: "つながる",
      follow: "フォロー",
      subscribe: "購読",
      join: "参加",
      apply: "応募",
      register: "登録",
      login: "ログイン",
      logout: "ログアウト",
      signup: "サインアップ",
      forgotPassword: "パスワードを忘れた",
      resetPassword: "パスワードをリセット",
      changePassword: "パスワードを変更",
      updateProfile: "プロフィールを更新"
    },
    
    // Status Messages
    status: {
      messageSent: "メッセージが正常に送信されました！",
      messageError: "メッセージの送信に失敗しました。もう一度お試しください。",
      sending: "送信中...",
      loading: "読み込み中...",
      saving: "保存中...",
      updating: "更新中...",
      deleting: "削除中...",
      uploading: "アップロード中...",
      downloading: "ダウンロード中...",
      processing: "処理中...",
      connecting: "接続中...",
      disconnected: "切断されました",
      connected: "接続されました",
      online: "オンライン",
      offline: "オフライン",
      available: "利用可能",
      unavailable: "利用不可",
      busy: "ビジー",
      away: "離席中"
    },
    
    // Error Messages
    errors: {
      required: "この項目は必須です",
      invalidEmail: "有効なメールアドレスを入力してください",
      invalidPhone: "有効な電話番号を入力してください",
      invalidUrl: "有効なURLを入力してください",
      passwordMismatch: "パスワードが一致しません",
      passwordTooShort: "パスワードは8文字以上である必要があります",
      invalidFormat: "無効な形式です",
      fileTooLarge: "ファイルサイズが大きすぎます",
      unsupportedFile: "サポートされていないファイル形式です",
      networkError: "ネットワークエラーです。もう一度お試しください。",
      serverError: "サーバーエラーです。後でもう一度お試しください。",
      unauthorized: "認証が必要です",
      forbidden: "アクセスが拒否されました",
      notFound: "ページが見つかりません",
      timeout: "リクエストがタイムアウトしました",
      unknownError: "不明なエラーが発生しました"
    },
    
    // Success Messages
    success: {
      profileUpdated: "プロフィールが正常に更新されました",
      messageSent: "メッセージが正常に送信されました",
      fileUploaded: "ファイルが正常にアップロードされました",
      fileDownloaded: "ファイルが正常にダウンロードされました",
      changesSaved: "変更が正常に保存されました",
      itemDeleted: "項目が正常に削除されました",
      itemCreated: "項目が正常に作成されました",
      itemUpdated: "項目が正常に更新されました",
      passwordChanged: "パスワードが正常に変更されました",
      emailSent: "メールが正常に送信されました",
      registrationComplete: "登録が正常に完了しました",
      loginSuccessful: "ログインが正常に完了しました"
    },
    
    // Placeholder Text
    placeholders: {
      search: "検索...",
      enterName: "お名前を入力してください",
      enterEmail: "メールアドレスを入力してください",
      enterPhone: "電話番号を入力してください",
      enterMessage: "メッセージを入力してください",
      enterSubject: "件名を入力してください",
      enterPassword: "パスワードを入力してください",
      confirmPassword: "パスワードを確認してください",
      enterAddress: "住所を入力してください",
      enterCompany: "会社名を入力してください",
      enterPosition: "役職を入力してください",
      enterWebsite: "ウェブサイトURLを入力してください",
      selectCountry: "国を選択してください",
      selectLanguage: "言語を選択してください",
      selectTheme: "テーマを選択してください",
      uploadFile: "ファイルをアップロード",
      dragAndDrop: "ファイルをここにドラッグ＆ドロップ",
      noResults: "結果が見つかりません",
      noData: "データがありません"
    },
    
    // Tooltips
    tooltips: {
      downloadCV: "履歴書/レジュメをダウンロード",
      contactMe: "メッセージを送信",
      viewProfile: "完全なプロフィールを見る",
      connectLinkedIn: "LinkedInでつながる",
      followTwitter: "Twitterでフォロー",
      subscribeNewsletter: "ニュースレターを購読",
      shareProfile: "プロフィールを共有",
      copyEmail: "メールアドレスをコピー",
      copyPhone: "電話番号をコピー",
      viewLocation: "地図で見る",
      openWebsite: "ウェブサイトを訪問",
      downloadFile: "ファイルをダウンロード",
      previewFile: "ファイルをプレビュー",
      editItem: "この項目を編集",
      deleteItem: "この項目を削除",
      viewDetails: "詳細を見る",
      closeModal: "モーダルを閉じる",
      minimizeWindow: "ウィンドウを最小化",
      maximizeWindow: "ウィンドウを最大化",
      fullscreen: "フルスクリーンを切り替え"
    },
    
    // Accessibility
    accessibility: {
      menuButton: "ナビゲーションメニューを切り替え",
      closeButton: "閉じる",
      searchButton: "検索",
      languageButton: "言語を変更",
      themeButton: "テーマを切り替え",
      scrollToTop: "トップにスクロール",
      skipToContent: "メインコンテンツにスキップ",
      skipToNavigation: "ナビゲーションにスキップ",
      loadingSpinner: "コンテンツを読み込み中",
      errorIcon: "エラーが発生しました",
      successIcon: "操作が成功しました",
      warningIcon: "警告",
      infoIcon: "情報",
      helpIcon: "ヘルプ",
      settingsIcon: "設定",
      profileIcon: "ユーザープロフィール",
      notificationIcon: "通知",
      searchIcon: "検索",
      filterIcon: "フィルターオプション",
      sortIcon: "並び替えオプション",
      refreshIcon: "コンテンツを更新",
      downloadIcon: "ダウンロード",
      uploadIcon: "アップロード",
      shareIcon: "共有",
      printIcon: "印刷",
      exportIcon: "エクスポート",
      importIcon: "インポート",
      editIcon: "編集",
      deleteIcon: "削除",
      viewIcon: "表示",
      addIcon: "追加",
      removeIcon: "削除",
      saveIcon: "保存",
      cancelIcon: "キャンセル",
      backIcon: "戻る",
      forwardIcon: "進む",
      homeIcon: "ホームに移動",
      aboutIcon: "私についてに移動",
      contactIcon: "お問い合わせに移動",
      researchIcon: "研究に移動"
    }
  }
};

export type Language = 'en' | 'ja';
export type StaticContentKey = keyof typeof staticContent.en; 